
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --

#include <cdk/ast/all.h>


#ifdef __NODE_DECLARATIONS_ONLY__

namespace mml {

class block_node;
class declaration_node;
class evaluation_node;
class function_call_node;
class function_def_node;
class if_else_node;
class if_node;
class print_node;
class program_node;
class read_node;
class while_node;


} // namespace mml

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_mml_NODE_ALL_NODES_H__
#define __AUTOMATIC_mml_NODE_ALL_NODES_H__

#include "ast/block_node.h"
#include "ast/declaration_node.h"
#include "ast/evaluation_node.h"
#include "ast/function_call_node.h"
#include "ast/function_def_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/print_node.h"
#include "ast/program_node.h"
#include "ast/read_node.h"
#include "ast/while_node.h"


#endif /* !defined(__AUTOMATIC_mml_NODE_ALL_NODES_H__) */
#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

