
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_address_of_node(mml::address_of_node *const node, int lvl) = 0;
  virtual void do_block_node(mml::block_node *const node, int lvl) = 0;
  virtual void do_declaration_node(mml::declaration_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(mml::evaluation_node *const node, int lvl) = 0;
  virtual void do_function_call_node(mml::function_call_node *const node, int lvl) = 0;
  virtual void do_function_def_node(mml::function_def_node *const node, int lvl) = 0;
  virtual void do_identity_node(mml::identity_node *const node, int lvl) = 0;
  virtual void do_if_else_node(mml::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(mml::if_node *const node, int lvl) = 0;
  virtual void do_index_node(mml::index_node *const node, int lvl) = 0;
  virtual void do_input_node(mml::input_node *const node, int lvl) = 0;
  virtual void do_next_node(mml::next_node *const node, int lvl) = 0;
  virtual void do_nullptr_node(mml::nullptr_node *const node, int lvl) = 0;
  virtual void do_return_node(mml::return_node *const node, int lvl) = 0;
  virtual void do_sizeof_node(mml::sizeof_node *const node, int lvl) = 0;
  virtual void do_stack_alloc_node(mml::stack_alloc_node *const node, int lvl) = 0;
  virtual void do_stop_node(mml::stop_node *const node, int lvl) = 0;
  virtual void do_while_node(mml::while_node *const node, int lvl) = 0;
  virtual void do_write_node(mml::write_node *const node, int lvl) = 0;

#else
  void do_address_of_node(mml::address_of_node *const node, int lvl);
  void do_block_node(mml::block_node *const node, int lvl);
  void do_declaration_node(mml::declaration_node *const node, int lvl);
  void do_evaluation_node(mml::evaluation_node *const node, int lvl);
  void do_function_call_node(mml::function_call_node *const node, int lvl);
  void do_function_def_node(mml::function_def_node *const node, int lvl);
  void do_identity_node(mml::identity_node *const node, int lvl);
  void do_if_else_node(mml::if_else_node *const node, int lvl);
  void do_if_node(mml::if_node *const node, int lvl);
  void do_index_node(mml::index_node *const node, int lvl);
  void do_input_node(mml::input_node *const node, int lvl);
  void do_next_node(mml::next_node *const node, int lvl);
  void do_nullptr_node(mml::nullptr_node *const node, int lvl);
  void do_return_node(mml::return_node *const node, int lvl);
  void do_sizeof_node(mml::sizeof_node *const node, int lvl);
  void do_stack_alloc_node(mml::stack_alloc_node *const node, int lvl);
  void do_stop_node(mml::stop_node *const node, int lvl);
  void do_while_node(mml::while_node *const node, int lvl);
  void do_write_node(mml::write_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

