
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_block_node(mml::block_node *const node, int lvl) = 0;
  virtual void do_declaration_node(mml::declaration_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(mml::evaluation_node *const node, int lvl) = 0;
  virtual void do_function_call_node(mml::function_call_node *const node, int lvl) = 0;
  virtual void do_function_def_node(mml::function_def_node *const node, int lvl) = 0;
  virtual void do_if_else_node(mml::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(mml::if_node *const node, int lvl) = 0;
  virtual void do_print_node(mml::print_node *const node, int lvl) = 0;
  virtual void do_program_node(mml::program_node *const node, int lvl) = 0;
  virtual void do_read_node(mml::read_node *const node, int lvl) = 0;
  virtual void do_while_node(mml::while_node *const node, int lvl) = 0;

#else
  void do_block_node(mml::block_node *const node, int lvl);
  void do_declaration_node(mml::declaration_node *const node, int lvl);
  void do_evaluation_node(mml::evaluation_node *const node, int lvl);
  void do_function_call_node(mml::function_call_node *const node, int lvl);
  void do_function_def_node(mml::function_def_node *const node, int lvl);
  void do_if_else_node(mml::if_else_node *const node, int lvl);
  void do_if_node(mml::if_node *const node, int lvl);
  void do_print_node(mml::print_node *const node, int lvl);
  void do_program_node(mml::program_node *const node, int lvl);
  void do_read_node(mml::read_node *const node, int lvl);
  void do_while_node(mml::while_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

